services:
  k3s:
    # make sure to replace + with - from the
    # original release tag
    image: rancher/k3s:v1.32.0-k3s1
    restart: unless-stopped
    hostname: k3s
    command: server
    privileged: true
    environment: {}
      #- K3S_KUBECONFIG_MODE=666
    volumes:
    - k3s:/var/lib/rancher/k3s
    - /etc/timezone:/etc/timezone:ro
    - ./manifests:/var/lib/rancher/k3s/server/manifests/custom
    configs:
      - source: k3s-custom-dns
        target: /var/lib/rancher/k3s/server/manifests/custom/custom-dns.yaml
      - source: traefik-default-cert
        target: /var/lib/rancher/k3s/server/manifests/custom/traefik-default-cert.yaml
      - source: http-entry-ingress
        target: /var/lib/rancher/k3s/server/manifests/custom/http-entry-ingress.yaml
    networks:
      - backbone
    ports:
      - ${PRIVATE_IP:?}:6443:6443
      - ${PUBLIC_IP:?}:443:443
      - ${PUBLIC_IP:?}:80:80
  dns:
    image: coredns/coredns:latest
    restart: unless-stopped
    configs:
      - source: coredns-corefile
        target: /home/nonroot/Corefile
      - source: coredns-zone
        target: /home/nonroot/domain.zone
    networks:
      backbone:
        ipv4_address: 10.10.8.99
    ports:
      - ${PRIVATE_IP:?}:1053:53/udp

networks:
  backbone:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.8.0/24
          gateway: 10.10.8.1

volumes:
  k3s: {}

configs:
  coredns-corefile:
    content: |
      ${DOMAIN:?}:53 {
        file domain.zone
        log
      }
  coredns-zone:
    content: |
      $$ORIGIN ${DOMAIN:?}.
      $$TTL 3600
      @	IN	SOA ${DOMAIN:?}. dns.${DOMAIN:?}. (
                      20250001   ; serial
                      7200       ; refresh (2 hours)
                      3600       ; retry (1 hour)
                      1209600    ; expire (2 weeks)
                      3600       ; minimum (1 hour)
      )

      @     IN A     ${PUBLIC_IP:?}
      *     IN A     ${PUBLIC_IP:?}
  k3s-custom-dns:
    content: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: coredns-custom
        namespace: kube-system
      data:
        ${DOMAIN:?}.server: |
          ${DOMAIN:?}:53 {
            forward . 10.10.8.99
          }
  traefik-default-cert:
    content: |
      apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: traefik-default-cert
        namespace: kube-system
      spec:
        secretName: traefik-default-cert-tls
        dnsNames:
          - "${DOMAIN:?}"
          - "*.${DOMAIN:?}"
        issuerRef:
          name: default-issuer
          kind: ClusterIssuer
  http-entry-ingress:
    content: |
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: http-entry
        namespace: http-entry
        labels:
          app.kubernetes.io/name: http-entry
      spec:
        rules:
          - host: ${DOMAIN:?}
            http:
              paths:
                - path: /
                  pathType: ImplementationSpecific
                  backend:
                    service:
                      name: http-entry
                      port:
                        number: 80