apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  repo: https://charts.jetstack.io
  chart: cert-manager
  targetNamespace: cert-manager
  createNamespace: true
  valuesContent: |
    crds:
      enabled: true
      keep: true
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Certificate
metadata:
  name: root-ca
  namespace: cert-manager
spec:
  isCA: true
  secretTemplate:
    stringData:
      tls.crt: $(certificate)
      tls.key: $(privateKey)
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: default-issuer
  namespace: cert-manager
spec:
  ca:
    secretName: root-ca
---
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: root-ca-cert
  namespace: cert-manager
spec:
  inputResources:
    - name: root-ca
      ref:
        apiVersion: v1
        kind: Secret
        name: root-ca
  template:
    data:
      ca.pem: $(.root-ca.data.tls\.crt)
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: root-ca-cert
  namespace: cert-manager
spec:
  toNamespace: "*"
