apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-default-cert
  namespace: kube-system
spec:
  secretName: traefik-default-cert-tls
  dnsNames:
    - "my-project.intern"
    - "*.my-project.intern"
  issuerRef:
    name: default-issuer
    kind: ClusterIssuer
